apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ml-system-failover
spec:
  host: ml-scaling-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ml-system-routing
spec:
  hosts:
  - ml-scaling-service
  http:
  - route:
    - destination:
        host: ml-scaling-service
        subset: primary-region
      weight: 90
    - destination:
        host: ml-scaling-service
        subset: backup-region
      weight: 10
    retries:
      attempts: 3
      perTryTimeout: 2s 