apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-metrics-adapter
  namespace: ml-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-metrics-adapter
  template:
    metadata:
      labels:
        app: ml-metrics-adapter
    spec:
      serviceAccountName: metrics-adapter-sa
      containers:
      - name: adapter
        image: ml-metrics-adapter:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-adapter-sa
  namespace: ml-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-adapter-role
rules:
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"] 