apiVersion: v1
kind: Service
metadata:
  name: ml-metrics-service
  namespace: ml-system
  labels:
    app: ml-metrics-adapter
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
  selector:
    app: ml-metrics-adapter 