apiVersion: grafana.integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:latest
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - ml-system 