apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-test
  namespace: testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - ml-system
    labelSelectors:
      "app": "ml-scaling"
  scheduler:
    cron: "@every 10m" 