apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-node
spec:
  serviceName: ipfs
  replicas: 3
  template:
    spec:
      containers:
      - name: ipfs
        image: ipfs/kubo:latest 