apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-config
  namespace: blockchain
data:
  config: |
    {
      "Addresses": {
        "Swarm": [
          "/ip4/0.0.0.0/tcp/4001",
          "/ip4/0.0.0.0/tcp/8081/ws"
        ],
        "API": "/ip4/0.0.0.0/tcp/5001",
        "Gateway": "/ip4/0.0.0.0/tcp/8080"
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs
  namespace: blockchain
spec:
  serviceName: ipfs
  replicas: 3
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: ipfs/kubo:latest
        ports:
        - name: swarm
          containerPort: 4001
        - name: api
          containerPort: 5001
        - name: gateway
          containerPort: 8080
        volumeMounts:
        - name: ipfs-storage
          mountPath: /data/ipfs
        - name: ipfs-config
          mountPath: /data/ipfs/config
          subPath: config
  volumeClaimTemplates:
  - metadata:
      name: ipfs-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi 